/*
* ========================================================================== *
*                                                                            *
*    This file is part of the Openterface Mini KVM App QT version            *
*                                                                            *
*    Copyright (C) 2024   <info@openterface.com>                             *
*                                                                            *
*    This program is free software: you can redistribute it and/or modify    *
*    it under the terms of the GNU General Public License as published by    *
*    the Free Software Foundation version 3.                                 *
*                                                                            *
*    This program is distributed in the hope that it will be useful, but     *
*    WITHOUT ANY WARRANTY; without even the implied warranty of              *
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU        *
*    General Public License for more details.                                *
*                                                                            *
*    You should have received a copy of the GNU General Public License       *
*    along with this program. If not, see <http://www.gnu.org/licenses/>.    *
*                                                                            *
* ========================================================================== *
*/

#include "SystemKeyBlocker.h"

#include <windows.h>
#include <QLoggingCategory>
#include <QMetaObject>
#include <QAbstractEventDispatcher>

Q_LOGGING_CATEGORY(log_syskey_win, "opf.systemkey.win")

/* ============================================================================
 *  Static self-pointer
 *
 *  WH_KEYBOARD_LL hook proc is a C-style callback — no `this`.  We store
 *  the current active instance so the hook can reach it.
 * ============================================================================ */
SystemKeyBlocker *SystemKeyBlocker::s_self = nullptr;

/* ============================================================================
 *  startImpl / stopImpl
 * ============================================================================ */

bool SystemKeyBlocker::startImpl(quintptr nativeParentHwnd)
{
    Q_ASSERT(!s_self || s_self == this);
    s_self = this;
    m_hookedHwnd = nativeParentHwnd;

    HINSTANCE hInst = GetModuleHandle(nullptr);
    HHOOK hook = SetWindowsHookEx(
        WH_KEYBOARD_LL,
        lowLevelKeyboardProc,
        hInst,
        0                    // hMod = 0 and dwThreadId = 0 → global hook
    );

    if (!hook) {
        DWORD err = GetLastError();
        qCCritical(log_syskey_win)
            << "SetWindowsHookEx(WH_KEYBOARD_LL) failed, error =" << err;
        s_self = nullptr;
        return false;
    }

    m_hHook = hook;
    qCInfo(log_syskey_win) << "Low-level keyboard hook installed (HWND:"
                           << nativeParentHwnd << ")";
    return true;
}

void SystemKeyBlocker::stopImpl()
{
    if (m_hHook) {
        UnhookWindowsHookEx(static_cast<HHOOK>(m_hHook));
        m_hHook = nullptr;
        qCInfo(log_syskey_win) << "Low-level keyboard hook removed";
    }
    s_self = nullptr;
}

/* ============================================================================
 *  Low-level keyboard hook callback
 *
 *  IMPORTANT — runs on a **system thread**, not the Qt event thread.
 *  - Must return within ~10 ms or the system will unhook us.
 *  - We do the absolute minimum here: classify the event, emit the signal
 *    (Qt marshals it across threads), and return.
 *  - Key-down events are swallowed (return 1).  Key-up events are passed
 *    through to avoid stuck keys in the OS.  Same strategy as VirtualBox.
 * ============================================================================ */

LRESULT CALLBACK SystemKeyBlocker::lowLevelKeyboardProc(
    int nCode, WPARAM wParam, LPARAM lParam)
{
    if (nCode != HC_ACTION || !s_self || !s_self->m_active) {
        return CallNextHookEx(nullptr, nCode, wParam, lParam);
    }

    const auto *kb = reinterpret_cast<KBDLLHOOKSTRUCT *>(lParam);
    const bool isKeyDown   = (wParam == WM_KEYDOWN || wParam == WM_SYSKEYDOWN);
    const bool isExtended  = (kb->flags & LLKHF_EXTENDED) != 0;
    const bool wasInjected = (kb->flags & LLKHF_INJECTED)  != 0;
    const quint32 vk       = kb->vkCode;

    // Let injected events pass through — they were generated by another
    // application (e.g. on-screen keyboard, automation tool), not by
    // physical keystrokes the user intends for the target.
    if (wasInjected) {
        return CallNextHookEx(nullptr, nCode, wParam, lParam);
    }

    // ---- Build modifier mask (GetAsyncKeyState for current physical state) ----
    int modifiers = 0;
    if (GetAsyncKeyState(VK_SHIFT)    & 0x8000) modifiers |= Qt::ShiftModifier;
    if (GetAsyncKeyState(VK_CONTROL)  & 0x8000) modifiers |= Qt::ControlModifier;
    if (GetAsyncKeyState(VK_MENU)     & 0x8000) modifiers |= Qt::AltModifier;
    if ((GetAsyncKeyState(VK_LWIN)    & 0x8000) ||
        (GetAsyncKeyState(VK_RWIN)    & 0x8000)) modifiers |= Qt::MetaModifier;

    // ---- Translate to Qt key code ----
    const int qtKey = s_self->nativeToQtKey(vk, isExtended);

    // ---- Emit signal (cross-thread dispatch by Qt) ----
    emit s_self->keyCaptured(qtKey, modifiers, isKeyDown, vk);

    // ---- Swallow key-down, pass key-up through ----
    // Letting the OS see releases prevents the OS from believing a key
    // is stuck.  VirtualBox uses the same approach.
    if (isKeyDown) {
        return 1;   // swallowed — OS does not process this key press
    }

    return CallNextHookEx(nullptr, nCode, wParam, lParam);
}

