name: Clazy Analysis for OpenterfaceQT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clazy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt 6.5.3
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          host: 'linux'
          arch: 'gcc_64'
          modules: 'qtmultimedia qtserialport'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clazy \
            libusb-1.0-0-dev \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libswscale-dev \
            libavdevice-dev

      - name: Build project
        run: |
          mkdir build
          cd build
          qmake ..
          make

      - name: Run Clazy
        run: |
          cd build
          clazy-standalone -p . > clazy_results.txt 2>&1

      - name: Convert Clazy results to HTML
        run: |
          pip install clang-tidy-html
          clang-tidy-html build/clazy_results.txt -o clazy_report.html

      - name: Checkout gh-pages branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan gh-pages

      - name: Copy HTML report
        run: |
          mv clazy_report.html index.html
          git add index.html
          git commit -m "Update Clazy report"

      - name: Push to gh-pages
        run: |
          git push --force origin gh-pages