---
name: Linux Build

on:
  push:
    branches: ['main', 'dev']
    tags: ['v*']
  pull_request:
<<<<<<< HEAD
    branches:
    - 'dev'

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.4.2
  ARTIFACT:     OpenterfaceQT
=======
    branches: ['dev']
>>>>>>> e201c3b (test(linux): test actions --- start ---)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.4.2'
        host: 'ubuntu'
        target: 'desktop'
        arch: 'gcc_64'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential fakeroot devscripts lintian

    - name: Build project
      run: |
        mkdir build
        cd build
        qmake6 ..
        make -j $(nproc)

    - name: Create deb package
      run: |
        mkdir -p build/deb/usr/local/bin
        cp build/your_executable build/deb/usr/local/bin/
        mkdir -p build/deb/DEBIAN
        echo "Package: openterfaceqt
        Version: ${GITHUB_REF#refs/tags/}
        Section: base
        Priority: optional
        Architecture: all
        Depends: libqt6core6 (>= 6.4.2), libqt6multimedia6 (>= 6.4.2), libqt6serialport6 (>= 6.4.2)
        Maintainer: TechXArtisan <info@techxartisan.com>
        Description: OpenterfaceQT" > build/deb/DEBIAN/control
        dpkg-deb --build build/deb

<<<<<<< HEAD
      - name: Configure And Build
        working-directory: ${{ runner.temp }}\build
        run:  |
          qmake6 ${{ github.workspace }} && make -j$(nproc)
          
      - name: Create deb package
        working-directory: ${{ runner.temp }}
        run: |
          mkdir -p package/DEBIAN
          # Create control file with package information
          echo "Package: ${{ env.ARTIFACT }}
          Version: 0.0.1
          Section: base
          Priority: optional
          Architecture: all
          Maintainer: TechXArtisan <info@techxartisan.com>
          Description: OpenterfaceQT" > package/DEBIAN/control
          # Copy files to package directory
          cp -r ${{ runner.temp }}/build/* package/
          # Build deb package
          mv package ${{ env.ARTIFACT }}
          dpkg-deb --build ${{ env.ARTIFACT }}
              
      - name: Create build directory
        run:  mkdir ${{ runner.temp }}\build

      - name: Configure And Build
        working-directory: ${{ runner.temp }}\build
        run:  |
          qmake && make -j$(nproc)
          cp ${{ github.workspace }}\build\bin\${{ env.ARTIFACT }} ${{ github.workspace }}\${{ env.ARTIFACT }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}/${{ env.ARTIFACT }}.deb
=======
    - name: Rename and move deb package for upload
      run: mv build/deb.deb build/openterfaceqt_${GITHUB_REF#refs/tags/}.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: deb-package
        path: build/openterfaceqt_${GITHUB_REF#refs/tags/}.deb
>>>>>>> e201c3b (test(linux): test actions --- start ---)
