name: Linux flatpak build

on:
  push:
    branches: ["main","dev_20250410_flatpak_publish"]
    tags: ["v*"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

env:
  ARTIFACT: openterfaceQT
  SOURCE_DIR: ${{ github.workspace }}
  FLATPAK_MANIFEST: "org.openterface.openterfaceQT.yaml"
  FLATPAK_BUILD_DIR: "build-dir"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install flatpak
        run: |
          sudo apt update -y
          sudo apt install -y flatpak flatpak-builder

      - name: Install prerequisites
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install build-essential
          sudo apt-get install -y libusb-1.0-0-dev rpm libfuse2
          
          wget -O linuxdeploy-x86_64.AppImage https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget -O linuxdeploy-plugin-qt-x86_64.AppImage https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          
          chmod +x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage appimagetool
          sudo mv linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage appimagetool /usr/local/bin/

      - name: Install Qt for AMD64
        if: matrix.arch == 'amd64'
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: linux
          target: desktop
          arch: gcc_64
          modules: qtmultimedia qtserialport

      

      - name: Install Qt for ARM64
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-multimedia-dev libqt6svg6-dev libqt6serialport6-dev libgl1-mesa-dev qt6-l10n-tools qt6-tools-dev qt6-tools-dev-tools
          echo "Qt6_DIR=/usr/lib/aarch64-linux-gnu/cmake/Qt6" >> $GITHUB_ENV
          echo "QTDIR=/usr/lib/aarch64-linux-gnu/qt6" >> $GITHUB_ENV
          echo "PATH=/usr/lib/qt6/bin:$PATH" >> $GITHUB_ENV

      - name: Add Flathub repository and install kde
        run: |
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak install --user --noninteractive flathub org.kde.Sdk/${{ matrix.arch }}/6.7
          flatpak install --user --noninteractive flathub org.kde.Platform/${{ matrix.arch }}/6.7
      
      - name: Run lupdate and lrelease
        run: |
          lupdate openterfaceQT.pro -no-obsolete
          lrelease openterfaceQT.pro

      - name: Initialize build directory
        run: |
          flatpak build-init $FLATPAK_BUILD_DIR org.openterface.openterfaceQT org.kde.Sdk org.kde.Platform 6.7

      - name: Build Flatpak
        run: |
          flatpak-builder \
            --user \
            --install \
            --force-clean \
            --repo=repo \
            --subject="Build of ${ARTIFACT}" \
            $FLATPAK_BUILD_DIR \
            $FLATPAK_MANIFEST